name: linting, testing, building
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 17.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Build production project
        run: make build-prod
      - name: Linting
        run: make lint
      - name: Unit testing
        run: make test-unit
      - name: Build storybook
        run: make storybook-build
      - name: Screenshot testing
        run: npm run test:ui:ci
